export const CREATE_COLLAB_REQUEST = "CREATE_COLLAB_REQUEST"
export const CREATE_COLLAB_SUCCESS = "CREATE_COLLAB_SUCCESS"
export const CREATE_COLLAB_FAIL = "CREATE_COLLAB_FAIL"
export const COLLAB_RESET = "COLLAB_RESET"

export const JOIN_COLLAB_REQUEST = "JOIN_COLLAB_REQUEST"
export const JOIN_COLLAB_SUCCESS = "JOIN_COLLAB_SUCCESS"
export const JOIN_COLLAB_FAIL = "JOIN_COLLAB_FAIL"

export const LEAVE_COLLAB_REQUEST = "LEAVE_COLLAB_REQUEST"
export const LEAVE_COLLAB_SUCCESS = "LEAVE_COLLAB_SUCCESS"
export const LEAVE_COLLAB_FAIL = "LEAVE_COLLAB_FAIL"
