export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST"
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS"
export const CREATE_PLAYLIST_FAIL = "CREATE_PLAYLIST_FAIL"
export const PLAYLIST_RESET = "PLAYLIST_RESET"
