export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST"
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS"
export const CREATE_PLAYLIST_FAIL = "CREATE_PLAYLIST_FAIL"
export const PLAYLIST_RESET = "PLAYLIST_RESET"

export const ADD_POST_PLAYLIST_REQUEST = "ADD_POST_PLAYLIST_REQUEST"
export const ADD_POST_PLAYLIST_SUCCESS = "ADD_POST_PLAYLIST_SUCCESS"
export const ADD_POST_PLAYLIST_FAIL = "ADD_POST_PLAYLIST_FAIL"

export const GET_PLAYLIST_REQUEST = "GET_PLAYLIST_REQUEST"
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS"
export const GET_PLAYLIST_FAIL = "GET_PLAYLIST_FAIL"
export const GET_PLAYLIST_RESET = "GET_PLAYLIST_RESET"

export const DELETE_PLAYLIST_REQUEST = "DELETE_PLAYLIST_REQUEST"
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS"
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL"
