export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAIL = "CREATE_POST_FAIL"
export const POST_RESET = "POST_RESET"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAIL = "GET_POST_FAIL"
export const GET_POST_RESET = "GET_POST_RESET"

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"
export const GET_POSTS_RESET = "GET_POSTS_RESET"

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST"
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS"
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL"

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST"
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL"

export const REPORT_POST_REQUEST = "REPORT_POST_REQUEST"
export const REPORT_POST_SUCCESS = "REPORT_POST_SUCCESS"
export const REPORT_POST_FAIL = "REPORT_POST_FAIL"

export const FLAG_POST_REQUEST = "FLAG_POST_REQUEST"
export const FLAG_POST_SUCCESS = "FLAG_POST_SUCCESS"
export const FLAG_POST_FAIL = "FLAG_POST_FAIL"

export const CREATE_COMIC_REQUEST = "CREATE_COMIC_REQUEST"
export const CREATE_COMIC_SUCCESS = "CREATE_COMIC_SUCCESS"
export const CREATE_COMIC_FAIL = "CREATE_COMIC_FAIL"

export const GET_COMICS_REQUEST = "GET_COMICS_REQUEST"
export const GET_COMICS_SUCCESS = "GET_COMICS_SUCCESS"
export const GET_COMICS_FAIL = "GET_COMICS_FAIL"
export const GET_COMICS_RESET = "GET_COMICS_RESET"

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST"
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS"
export const LIKE_POST_FAIL = "LIKE_POST_FAIL"

export const SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST"
export const SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS"
export const SEARCH_POST_FAIL = "SEARCH_POST_FAIL"
