export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAIL = "CREATE_POST_FAIL"
export const POST_RESET = "POST_RESET"

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"
export const GET_POSTS_RESET = "GET_POSTS_RESET"

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST"
export const GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS"
export const GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL"

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST"
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL"

export const REPORT_POST_REQUEST = "REPORT_POST_REQUEST"
export const REPORT_POST_SUCCESS = "REPORT_POST_SUCCESS"
export const REPORT_POST_FAIL = "REPORT_POST_FAIL"

export const FLAG_POST_REQUEST = "FLAG_POST_REQUEST"
export const FLAG_POST_SUCCESS = "FLAG_POST_SUCCESS"
export const FLAG_POST_FAIL = "FLAG_POST_FAIL"
