export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"
export const USER_DETAILS_RESET = "USER_DETAILS_RESET"

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST"
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS"
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL"
export const USER_RESET_PROFILE = "USER_RESET_PROFILE"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"

export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"

export const GET_USER_POST_REQUEST = "GET_USER_POST_REQUEST"
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS"
export const GET_USER_POST_FAIL = "GET_USER_POST_FAIL"

export const CHANGE_ROLE_REQUEST = "CHANGE_ROLE_REQUEST"
export const CHANGE_ROLE_SUCCESS = "CHANGE_ROLE_SUCCESS"
export const CHANGE_ROLE_FAIL = "CHANGE_ROLE_FAIL"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL"

export const UNFOLLOW_USER_REQUEST = "UNFOLLOW_USER_REQUEST"
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS"
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL"

export const GET_BLOCKED_USERS_REQUEST = "GET_BLOCKED_USERS_REQUEST"
export const GET_BLOCKED_USERS_SUCCESS = "GET_BLOCKED_USERS_SUCCESS"
export const GET_BLOCKED_USERS_FAIL = "GET_BLOCKED_USERS_FAIL"

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST"
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS"
export const BLOCK_USER_FAIL = "BLOCK_USER_FAIL"

export const UNBLOCK_USER_REQUEST = "UNBLOCK_USER_REQUEST"
export const UNBLOCK_USER_SUCCESS = "UNBLOCK_USER_SUCCESS"
export const UNBLOCK_USER_FAIL = "UNBLOCK_USER_FAIL"

export const BAN_USER_REQUEST = "BAN_USER_REQUEST" //ahmed
export const BAN_USER_SUCCESS = "BAN_USER_SUCCESS" //ahmed
export const BAN_USER_FAIL = "BAN_USER_FAIL" //ahmed

export const GET_USER_PLAYLISTS_REQUEST = "GET_USER_PLAYLISTS_REQUEST"
export const GET_USER_PLAYLISTS_SUCCESS = "GET_USER_PLAYLISTS_SUCCESS"
export const GET_USER_PLAYLISTS_FAIL = "GET_USER_PLAYLISTS_FAIL"
export const GET_USER_PLAYLISTS_RESET = "GET_USER_PLAYLISTS_RESET"
